version: "3"
services:
  backend:
    image: node:alpine
    volumes:
      - "./backend:/code"
    working_dir: /code
    entrypoint: ["npm", "run", "watch"]
    ports:
      - "4000:4000"
  frontend:
    #build: frontend
    image: node:alpine
    volumes:
      - "./frontend:/code"
    working_dir: /code
    entrypoint: ["npm", "start"]
    ports:
      - "3000:3000"
  db:
    image: mongo
